ls:
  config:
    .js: kebab-case | point.case
    .ts: kebab-case | point.case
    .config.js: kebab-case
    .config.ts: kebab-case
  build:
    .js: kebab-case
    .ts: kebab-case
    .config.js: kebab-case
    .config.ts: kebab-case
  mock:
    .js: kebab-case
    .ts: kebab-case
  src:
    .js: kebab-case
    .ts: kebab-case
    .d.ts: kebab-case
    .config.js: kebab-case
    .config.ts: kebab-case
    .jsx: kebab-case
    .tsx: kebab-case
    .vue: kebab-case
    .css: kebab-case
    .less: kebab-case
    .sass: kebab-case
    .scss: kebab-case
    .module.css: kebab-case
    .module.less: kebab-case
    .module.sass: kebab-case
    .module.scss: kebab-case
  src/composables:
    .js: camelCase
    .ts: camelCase
  src/hooks:
    .js: camelCase
    .ts: camelCase
  src/**/components:
    .jsx: PascalCase | kebab-case
    .tsx: PascalCase | kebab-case
    .vue: PascalCase | kebab-case
  src/**/test:
    .js: kebab-case | camelCase
    .ts: kebab-case | camelCase
    .spec.js: kebab-case | camelCase
    .spec.ts: kebab-case | camelCase
    .test.js: kebab-case | camelCase
    .test.ts: kebab-case | camelCase
  src/**/__test__:
    .js: kebab-case | camelCase
    .ts: kebab-case | camelCase
    .spec.js: kebab-case | camelCase
    .spec.ts: kebab-case | camelCase
    .test.js: kebab-case | camelCase
    .test.ts: kebab-case | camelCase
  src/**/tests:
    .js: kebab-case | camelCase
    .ts: kebab-case | camelCase
    .spec.js: kebab-case | camelCase
    .spec.ts: kebab-case | camelCase
    .test.js: kebab-case | camelCase
    .test.ts: kebab-case | camelCase
  src/**/__tests__:
    .js: kebab-case | camelCase
    .ts: kebab-case | camelCase
    .spec.js: kebab-case | camelCase
    .spec.ts: kebab-case | camelCase
    .test.js: kebab-case | camelCase
    .test.ts: kebab-case | camelCase
  pages:
    .js: kebab-case
    .ts: kebab-case
    .d.ts: kebab-case
    .config.js: kebab-case
    .config.ts: kebab-case
    .jsx: kebab-case
    .tsx: kebab-case
    .vue: kebab-case
    .css: kebab-case
    .less: kebab-case
    .sass: kebab-case
    .scss: kebab-case
    .module.css: kebab-case
    .module.less: kebab-case
    .module.sass: kebab-case
    .module.scss: kebab-case
  store:
    .js: kebab-case
    .ts: kebab-case
  styles:
    .css: kebab-case
    .less: kebab-case
    .sass: kebab-case
    .scss: kebab-case
    .module.css: kebab-case
    .module.less: kebab-case
    .module.sass: kebab-case
    .module.scss: kebab-case
  typings:
    .js: kebab-case
    .ts: kebab-case
    .d.ts: kebab-case
  types:
    .js: kebab-case
    .ts: kebab-case
    .d.ts: kebab-case
  test:
    .js: kebab-case | camelCase
    .ts: kebab-case | camelCase
    .spec.js: kebab-case | camelCase
    .spec.ts: kebab-case | camelCase
    .test.js: kebab-case | camelCase
    .test.ts: kebab-case | camelCase
  __test__:
    .js: kebab-case | camelCase
    .ts: kebab-case | camelCase
    .spec.js: kebab-case | camelCase
    .spec.ts: kebab-case | camelCase
    .test.js: kebab-case | camelCase
    .test.ts: kebab-case | camelCase
  tests:
    .js: kebab-case | camelCase
    .ts: kebab-case | camelCase
    .spec.js: kebab-case | camelCase
    .spec.ts: kebab-case | camelCase
    .test.js: kebab-case | camelCase
    .test.ts: kebab-case | camelCase
  __tests__:
    .js: kebab-case | camelCase
    .ts: kebab-case | camelCase
    .spec.js: kebab-case | camelCase
    .spec.ts: kebab-case | camelCase
    .test.js: kebab-case | camelCase
    .test.ts: kebab-case | camelCase

ignore:
  - ./src/.next
  - ./src/.nuxt
  - ./src/.rax
  - ./src/.umi
  - ./src/App.js
  - ./src/App.ts
  - ./src/App.jsx
  - ./src/App.tsx
  - ./src/App.vue
  - ./src/App.css
  - ./src/App.less
  - ./src/App.sass
  - ./src/App.scss
